@FeedServer_HostAddress = http://localhost:5137
@FeedGuid = 4cb82df9-f198-40d8-8f11-fc59365e28a2
@ReaderGuid = 0576e9fc-75d5-4620-9d72-a7ff33d859de

GET {{FeedServer_HostAddress}}/{{FeedGuid}}
Accept: text/plain

###

POST {{FeedServer_HostAddress}}/{{FeedGuid}}
Content-Type: text/plain

hello feed

###

GET {{FeedServer_HostAddress}}/{{FeedGuid}}/{{ReaderGuid}}
Accept: text/plain

###

GET {{FeedServer_HostAddress}}/not-a-guid
Accept: application/problem+json

###

GET {{FeedServer_HostAddress}}/{{FeedGuid}}
Authorization: Basic dXNlcjpwYXNz
Accept: application/problem+json

###

GET {{FeedServer_HostAddress}}/56d248ae-8723-4e33-b56c-02e290f8bf84
Authorization: Basic dXNlcjpwYXNz
Accept: text/plain

###
